// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1xNZSYxkII1NqT8Q4kxm8MSe0KAHLJ-8',
    appId: '1:829517273361:web:c7b54ad78dad37575314b0',
    messagingSenderId: '829517273361',
    projectId: 'crickket-4cc00',
    authDomain: 'crickket-4cc00.firebaseapp.com',
    storageBucket: 'crickket-4cc00.appspot.com',
    measurementId: 'G-5TBCG6762X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQBwWv4n5LlTYhxg-eNyDUsI2TqMFKZxk',
    appId: '1:829517273361:android:107530bb596fcd445314b0',
    messagingSenderId: '829517273361',
    projectId: 'crickket-4cc00',
    storageBucket: 'crickket-4cc00.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGj26ONfh8XRUNipCSAgk8vdJZgxdcNO0',
    appId: '1:829517273361:ios:85771553e0555d215314b0',
    messagingSenderId: '829517273361',
    projectId: 'crickket-4cc00',
    storageBucket: 'crickket-4cc00.appspot.com',
    iosBundleId: 'com.example.cricket.RunnerTests',
  );
}
